[tool.poetry]
name = "aoc-2020"
version = "0.1.0"
description = ""
authors = ["Ben Ward <bw@ben-ward.net>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"
